### PR TITLE
feat: initial draft implementation of basic xml matching + diff formatting

### PR DESCRIPTION
**Pull request by uldissturms**

### CODE REVIEW

**Review by bethesque — COMMENTED** [review]
I reckon if the XML cannot be parsed, raise an error.

**Review by bethesque — COMMENTED** [review]
Do I need to add the message in the equality check for Difference?

**Comment by uldissturms** [comment]
Cool, @bethesque, I will add the error handling - re-throw of custom error with more details.
Not sure I get the second point - mind referring to file & line?

**Comment by bethesque** [comment]
I noticed that this was being checked in two parts

```
+              it "returns diff" do
+                expect(subject).to eq([Difference.new("tag", "x")])
+              end
+              it "returns message with path" do
+                expect(subject.first.message).to eq("Expected Element tag but got x at $.tag")
+              end
```

I suspect that I left the message out of the equality method.

**Comment by uldissturms** [comment]
Yes, I think it would make sense to add it, unless it breaks design somewhere.

**Comment by bethesque** [comment]
That field just got added after the original class, and I think I didn't want to have to update all the test cases to include the message as well!

**Comment by bethesque** [comment]
Do you want me to merge this now, or do you want to just keep pushing to this branch?

**Comment by uldissturms** [comment]
I would prefer if you merged, keen on seeing it plugged in end-to-end in the naive happy scenario.
Should we discuss next steps on how we could do that without the risk of unintentionally breaking other's code? Maybe on Slack? Then I can do some testing over weekend and get some more unhappy paths covered + work on rule support.

**Pull request merged**
